### PR TITLE
Fix issue when using multiple interfaces

### LINKED ISSUE #6: /tmp/wpa_ctrl socket deleted if the same process have multiple interfaces
Line [95](https://github.com/spease/wpa-ctrl-rs/blob/e37eeb0a9b58cde12bc9825515caaaadcbf49fa6/src/wpactrl.rs#L95) in wpactrl.rs deletes already existing wpa_ctrl sockets for the same process. This will result in a timeout on the [select ](https://github.com/spease/wpa-ctrl-rs/blob/master/src/wpactrl.rs#L159)if multiple  Wi-Fi interfaces (wpa_supplicants) are handled by the same application.

Deletion of line 95 resolves this issue,see my [fork](https://github.com/suhrm/wpa-ctrl-rs/commit/1b301a427425227e1376a6e7ed6f15a5ee8b40d7), however I have not checked if this introduces other side-effects.

Regards.

### PR DESCRIPTION
**Pull request by apbr**
Don't delete a socket that is already in use.
Fixes #6

### CODE REVIEW

**Comment by spease** [comment]
If you can update this so it matches the behavior of the original wpa_supplicant (Fix the tries/counter thing we're discussing in the other thread) and that works for your use case, I'll go ahead and merge it. I'd have to take the time to think through this to figure out whether it's >= the original stock solution, and this just isn't top of my priority list right now. Sorry for my delay in replying to both this and the other thread.

**Comment by apbr** [comment]
@spease Updated this so that it matches behavior of original wpa_supplicant.

**Comment by spease** [comment]
This looks good, but I would use atomics. The implementation will be simpler, no lazy_static dependency, and I think it will be more performant at least for CPUs that have built-in atomic instructions.

```
diff --git i/src/wpactrl.rs w/src/wpactrl.rs
index 792a018..b1ad1ea 100644
--- i/src/wpactrl.rs
+++ w/src/wpactrl.rs
@@ -1,12 +1,11 @@
 #![deny(missing_docs)]
 use super::Result;
-use lazy_static::lazy_static;
 use log::warn;
 use std::collections::VecDeque;
 use std::os::unix::io::{AsRawFd, RawFd};
 use std::os::unix::net::UnixDatagram;
 use std::path::{Path, PathBuf};
-use std::sync::Mutex;
+use std::sync::atomic::{AtomicUsize, Ordering};
 use std::time::Duration;

 use crate::error::Error;
@@ -16,9 +15,7 @@ const PATH_DEFAULT_CLIENT: &str = "/tmp";
 const PATH_DEFAULT_SERVER: &str = "/var/run/wpa_supplicant/wlan0";

 // Counter to avoid using the same file when creating multiple clients.
-lazy_static! {
-    static ref COUNTER: Mutex<u32> = Mutex::new(0);
-}
+static COUNTER: AtomicUsize = AtomicUsize::new(0);

 /// Builder object used to construct a [`Client`] session
 #[derive(Default)]
@@ -84,12 +81,11 @@ impl ClientBuilder {
     ///
     /// * [[`Error::Io`]] - Low-level I/O error
     pub fn open(self) -> Result<Client> {
-        let mut counter = COUNTER.lock().expect("Failed locking `counter` Mutex");
-        *counter += 1;
+        let counter = COUNTER.fetch_add(1, Ordering::SeqCst);
         let mut tries = 0;
         loop {
             tries += 1;
-            let bind_filename = format!("wpa_ctrl_{}-{}", std::process::id(), *counter);
+            let bind_filename = format!("wpa_ctrl_{}-{}", std::process::id(), counter);
             let bind_filepath = self
                 .cli_path
                 .as_deref()
```

I tested this change with the unit tests, let me know if you see any problems with it. Feel free to either update the PR or I can update after merging.

EDIT: Also the current `Mutex` impl, unless Rust drops it at the last use rather than the end of the function scope, will get held across system calls / context switching. The atomic will not.

**Comment by apbr** [comment]
Good point. I updated the PR.

**Review by spease — APPROVED** [review]

**Pull request merged**
